- name: Update the repository cache and update package "nginx" to latest version
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: start nginx
  service:
      name: nginx
      state: started
  become: yes

#- name: copy the nginx conf file and restart nginx
#  copy:
#   src: /etc/ansible/config/static_site.cfg
#   dest: /etc/nginx/nginx.conf
#  become: yes

#- name: copy the nginx config file and restart nginx
#  copy:
#    src: /etc/ansible/config/static_site.cfg
#    dest: /etc/nginx/sites-available/static_site.cfg
#  become: yes
              
#- name: create symlink
#  file:
#    src: /etc/nginx/sites-available/static_site.cfg
#    dest: /etc/nginx/sites-enabled/default
#    state: link
#  become: yes

#- name: copy the content of the web site
#  copy:
#    src: /home/foo/static-site-src/
#    dest: /home/foo/static-site
#  become: yes
